/*
This script has been generated by Nickk's TextDraw editor
Author is Nickk888
*/

//VARIABLES
new Text:playerid, gangtd_1[playerid][4];

//TEXTDRAWS



//SHOW/HIDE
TextDrawShowForPlayer(playerid, playerid, gangtd_1[playerid][4]); //Shows Textdraw for Player.
TextDrawShowForAll(playerid, gangtd_1[playerid][4]); //Shows Textdraw for all players.

TextDrawHideForPlayer(playerid, playerid, gangtd_1[playerid][4]); //Hides TextDraw for player.
TextDrawHideForAll(playerid, gangtd_1[playerid][4]); //Hides Textdraw for all players.

PlayerTextDrawShow(playerid, playerid, gangtd_1[playerid][4][playerid]); //Shows PlayerTextDraw for player.
PlayerTextDrawHide(playerid, playerid, gangtd_1[playerid][4][playerid]); //Hides PlayerTextDraw for player.
