/*
This script has been generated by Nickk's TextDraw editor
Author is Nickk888
*/

//VARIABLES
new Text:LGGW[0];
new Text:LGGW[2];
new Text:LGGW[5];
new PlayerText:fplabel_1[MAX_PLAYERS];
new Text:LGGW[1];

//TEXTDRAWS










//SHOW/HIDE
TextDrawShowForPlayer(playerid, LGGW[0]); //Shows Textdraw for Player.
TextDrawShowForAll(LGGW[0]); //Shows Textdraw for all players.

TextDrawHideForPlayer(playerid, LGGW[0]); //Hides TextDraw for player.
TextDrawHideForAll(LGGW[0]); //Hides Textdraw for all players.

PlayerTextDrawShow(playerid, LGGW[0][playerid]); //Shows PlayerTextDraw for player.
PlayerTextDrawHide(playerid, LGGW[0][playerid]); //Hides PlayerTextDraw for player.
