/*
This script has been generated by Nickk's TextDraw editor
Author is Nickk888
*/

//VARIABLES
new Text:connecttd[2];

//TEXTDRAWS
connecttd[2] = TextDrawCreate(0.000000, 0.000000, tds_);
TextDrawFont(connecttd[2], 4);
TextDrawLetterSize(connecttd[2], 0.600000, 2.000000);
TextDrawTextSize(connecttd[2], 640.500000, 447.000000);
TextDrawSetOutline(connecttd[2], 1);
TextDrawSetShadow(connecttd[2], 0);
TextDrawAlignment(connecttd[2], 1);
TextDrawColor(connecttd[2], -1);
TextDrawBackgroundColor(connecttd[2], 255);
TextDrawBoxColor(connecttd[2], 50);
TextDrawUseBox(connecttd[2], 1);
TextDrawSetProportional(connecttd[2], 1);
TextDrawSetSelectable(connecttd[2], 0);


//SHOW/HIDE
TextDrawShowForPlayer(playerid, connecttd[2]); //Shows Textdraw for Player.
TextDrawShowForAll(connecttd[2]); //Shows Textdraw for all players.

TextDrawHideForPlayer(playerid, connecttd[2]); //Hides TextDraw for player.
TextDrawHideForAll(connecttd[2]); //Hides Textdraw for all players.

PlayerTextDrawShow(playerid, connecttd[2][playerid]); //Shows PlayerTextDraw for player.
PlayerTextDrawHide(playerid, connecttd[2][playerid]); //Hides PlayerTextDraw for player.
