/*
This script has been generated by Nickk's TextDraw editor
Author is Nickk888
*/

//VARIABLES
new PlayerText:fonttd[MAX_PLAYERS];

//TEXTDRAWS
fonttd[playerid] = CreatePlayerTextDraw(playerid, 636.000000, 328.000000, "Font_ID:_1");
PlayerTextDrawFont(playerid, fonttd[playerid], 2);
PlayerTextDrawLetterSize(playerid, fonttd[playerid], 0.383332, 1.600000);
PlayerTextDrawTextSize(playerid, fonttd[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, fonttd[playerid], 1);
PlayerTextDrawSetShadow(playerid, fonttd[playerid], 0);
PlayerTextDrawAlignment(playerid, fonttd[playerid], 3);
PlayerTextDrawColor(playerid, fonttd[playerid], 16711935);
PlayerTextDrawBackgroundColor(playerid, fonttd[playerid], 255);
PlayerTextDrawBoxColor(playerid, fonttd[playerid], 50);
PlayerTextDrawUseBox(playerid, fonttd[playerid], 0);
PlayerTextDrawSetProportional(playerid, fonttd[playerid], 1);
PlayerTextDrawSetSelectable(playerid, fonttd[playerid], 0);


//SHOW/HIDE
TextDrawShowForPlayer(playerid, textdraw_0); //Shows Textdraw for Player.
TextDrawShowForAll(textdraw_0); //Shows Textdraw for all players.

TextDrawHideForPlayer(playerid, textdraw_0); //Hides TextDraw for player.
TextDrawHideForAll(textdraw_0); //Hides Textdraw for all players.

PlayerTextDrawShow(playerid, textdraw_0[playerid]); //Shows PlayerTextDraw for player.
PlayerTextDrawHide(playerid, textdraw_0[playerid]); //Hides PlayerTextDraw for player.
