/*
This script has been generated by Nickk's TextDraw editor
Author is Nickk888
*/

//VARIABLES
new PlayerText:killtext[MAX_PLAYERS];

//TEXTDRAWS



//SHOW/HIDE
TextDrawShowForPlayer(playerid, killtext); //Shows Textdraw for Player.
TextDrawShowForAll(killtext); //Shows Textdraw for all players.

TextDrawHideForPlayer(playerid, killtext); //Hides TextDraw for player.
TextDrawHideForAll(killtext); //Hides Textdraw for all players.

PlayerTextDrawShow(playerid, killtext[playerid]); //Shows PlayerTextDraw for player.
PlayerTextDrawHide(playerid, killtext[playerid]); //Hides PlayerTextDraw for player.
