/*
This script has been generated by Nickk's TextDraw editor
Author is Nickk888
*/

//VARIABLES
new Text:textdraw_0;
new PlayerText:textdraw_1[MAX_PLAYERS];
new PlayerText:textdraw_2[MAX_PLAYERS];
new PlayerText:textdraw_3[MAX_PLAYERS];
new Text:textdraw_4;

//TEXTDRAWS
textdraw_0 = TextDrawCreate(572.000000, 281.000000, "_");
TextDrawFont(textdraw_0, 1);
TextDrawLetterSize(textdraw_0, 0.649999, 7.849999);
TextDrawTextSize(textdraw_0, 297.500000, 90.500000);
TextDrawSetOutline(textdraw_0, 1);
TextDrawSetShadow(textdraw_0, 0);
TextDrawAlignment(textdraw_0, 2);
TextDrawColor(textdraw_0, -1);
TextDrawBackgroundColor(textdraw_0, 255);
TextDrawBoxColor(textdraw_0, 135);
TextDrawUseBox(textdraw_0, 1);
TextDrawSetProportional(textdraw_0, 1);
TextDrawSetSelectable(textdraw_0, 0);

textdraw_1[playerid] = CreatePlayerTextDraw(playerid, 573.000000, 304.000000, "gang_name_1~n~against");
PlayerTextDrawFont(playerid, textdraw_1[playerid], 1);
PlayerTextDrawLetterSize(playerid, textdraw_1[playerid], 0.287500, 1.350000);
PlayerTextDrawTextSize(playerid, textdraw_1[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, textdraw_1[playerid], 0);
PlayerTextDrawSetShadow(playerid, textdraw_1[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_1[playerid], 2);
PlayerTextDrawColor(playerid, textdraw_1[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, textdraw_1[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_1[playerid], 50);
PlayerTextDrawUseBox(playerid, textdraw_1[playerid], 0);
PlayerTextDrawSetProportional(playerid, textdraw_1[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_1[playerid], 0);

textdraw_2[playerid] = CreatePlayerTextDraw(playerid, 574.000000, 329.000000, "gang_name_2");
PlayerTextDrawFont(playerid, textdraw_2[playerid], 1);
PlayerTextDrawLetterSize(playerid, textdraw_2[playerid], 0.287500, 1.350000);
PlayerTextDrawTextSize(playerid, textdraw_2[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, textdraw_2[playerid], 0);
PlayerTextDrawSetShadow(playerid, textdraw_2[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_2[playerid], 2);
PlayerTextDrawColor(playerid, textdraw_2[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, textdraw_2[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_2[playerid], 50);
PlayerTextDrawUseBox(playerid, textdraw_2[playerid], 0);
PlayerTextDrawSetProportional(playerid, textdraw_2[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_2[playerid], 0);

textdraw_3[playerid] = CreatePlayerTextDraw(playerid, 527.000000, 290.000000, "time_left:_30");
PlayerTextDrawFont(playerid, textdraw_3[playerid], 2);
PlayerTextDrawLetterSize(playerid, textdraw_3[playerid], 0.162500, 1.300000);
PlayerTextDrawTextSize(playerid, textdraw_3[playerid], 617.000000, 17.500000);
PlayerTextDrawSetOutline(playerid, textdraw_3[playerid], 1);
PlayerTextDrawSetShadow(playerid, textdraw_3[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_3[playerid], 1);
PlayerTextDrawColor(playerid, textdraw_3[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, textdraw_3[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_3[playerid], 255);
PlayerTextDrawUseBox(playerid, textdraw_3[playerid], 1);
PlayerTextDrawSetProportional(playerid, textdraw_3[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_3[playerid], 0);

textdraw_4 = TextDrawCreate(526.000000, 270.000000, "turf_progress");
TextDrawFont(textdraw_4, 3);
TextDrawLetterSize(textdraw_4, 0.270833, 1.750000);
TextDrawTextSize(textdraw_4, 400.000000, 17.000000);
TextDrawSetOutline(textdraw_4, 1);
TextDrawSetShadow(textdraw_4, 0);
TextDrawAlignment(textdraw_4, 1);
TextDrawColor(textdraw_4, -1);
TextDrawBackgroundColor(textdraw_4, 255);
TextDrawBoxColor(textdraw_4, 50);
TextDrawUseBox(textdraw_4, 0);
TextDrawSetProportional(textdraw_4, 1);
TextDrawSetSelectable(textdraw_4, 0);


//SHOW/HIDE
TextDrawShowForPlayer(playerid, textdraw_0); //Shows Textdraw for Player.
TextDrawShowForAll(textdraw_0); //Shows Textdraw for all players.

TextDrawHideForPlayer(playerid, textdraw_0); //Hides TextDraw for player.
TextDrawHideForAll(textdraw_0); //Hides Textdraw for all players.

PlayerTextDrawShow(playerid, textdraw_0[playerid]); //Shows PlayerTextDraw for player.
PlayerTextDrawHide(playerid, textdraw_0[playerid]); //Hides PlayerTextDraw for player.
