/*
new Text:textdraw_11;

//TEXTDRAWS


textdraw_1 = TextDrawCreate(359.000000, 151.00000
This script has been generated by Nickk's TextDraw editor
Author is Nickk888
*/

//VARIABLES
new PlayerText:pleveltd[MAX_PLAYERS];
new Text:textdraw_1;
new Text:textdraw_2;
new Text:textdraw_3;
new Text:textdraw_4;
new Text:textdraw_5;
new Text:textdraw_6;
new Text:textdraw_7;
new Text:textdraw_8;
new Text:textdraw_9;
new Text:textdraw_10;0, "HUD:radardisc");
TextDrawFont(textdraw_1, 4);
TextDrawLetterSize(textdraw_1, 0.600000, 2.000000);
TextDrawTextSize(textdraw_1, 166.500000, 60.000000);
TextDrawSetOutline(textdraw_1, 1);
TextDrawSetShadow(textdraw_1, 0);
TextDrawAlignment(textdraw_1, 1);
TextDrawColor(textdraw_1, -1);
TextDrawBackgroundColor(textdraw_1, 255);
TextDrawBoxColor(textdraw_1, 50);
TextDrawUseBox(textdraw_1, 1);
TextDrawSetProportional(textdraw_1, 1);
TextDrawSetSelectable(textdraw_1, 0);

textdraw_2 = TextDrawCreate(516.000000, 147.000000, "ld_dual:dark");
TextDrawFont(textdraw_2, 4);
TextDrawLetterSize(textdraw_2, 0.600000, 2.000000);
TextDrawTextSize(textdraw_2, 16.500000, 16.500000);
TextDrawSetOutline(textdraw_2, 1);
TextDrawSetShadow(textdraw_2, 0);
TextDrawAlignment(textdraw_2, 1);
TextDrawColor(textdraw_2, -1);
TextDrawBackgroundColor(textdraw_2, 255);
TextDrawBoxColor(textdraw_2, 50);
TextDrawUseBox(textdraw_2, 1);
TextDrawSetProportional(textdraw_2, 1);
TextDrawSetSelectable(textdraw_2, 0);

textdraw_3 = TextDrawCreate(315.000000, 213.000000, "gang_level");
TextDrawFont(textdraw_3, 3);
TextDrawLetterSize(textdraw_3, 0.570833, 2.049998);
TextDrawTextSize(textdraw_3, 400.000000, 17.000000);
TextDrawSetOutline(textdraw_3, 0);
TextDrawSetShadow(textdraw_3, 0);
TextDrawAlignment(textdraw_3, 1);
TextDrawColor(textdraw_3, -1);
TextDrawBackgroundColor(textdraw_3, 255);
TextDrawBoxColor(textdraw_3, 50);
TextDrawUseBox(textdraw_3, 0);
TextDrawSetProportional(textdraw_3, 1);
TextDrawSetSelectable(textdraw_3, 0);

textdraw_4 = TextDrawCreate(359.000000, 151.000000, "HUD:radardisc");
TextDrawFont(textdraw_4, 4);
TextDrawLetterSize(textdraw_4, 0.600000, 2.000000);
TextDrawTextSize(textdraw_4, 166.500000, 60.000000);
TextDrawSetOutline(textdraw_4, 1);
TextDrawSetShadow(textdraw_4, 0);
TextDrawAlignment(textdraw_4, 1);
TextDrawColor(textdraw_4, -1);
TextDrawBackgroundColor(textdraw_4, 255);
TextDrawBoxColor(textdraw_4, 50);
TextDrawUseBox(textdraw_4, 1);
TextDrawSetProportional(textdraw_4, 1);
TextDrawSetSelectable(textdraw_4, 0);

textdraw_5 = TextDrawCreate(330.000000, 130.000000, "HUD:radardisc");
TextDrawFont(textdraw_5, 4);
TextDrawLetterSize(textdraw_5, 0.600000, 2.000000);
TextDrawTextSize(textdraw_5, 194.500000, -33.500000);
TextDrawSetOutline(textdraw_5, 1);
TextDrawSetShadow(textdraw_5, 0);
TextDrawAlignment(textdraw_5, 1);
TextDrawColor(textdraw_5, -1);
TextDrawBackgroundColor(textdraw_5, 255);
TextDrawBoxColor(textdraw_5, 50);
TextDrawUseBox(textdraw_5, 1);
TextDrawSetProportional(textdraw_5, 1);
TextDrawSetSelectable(textdraw_5, 0);

textdraw_6 = TextDrawCreate(515.000000, 119.000000, "ld_dual:dark");
TextDrawFont(textdraw_6, 4);
TextDrawLetterSize(textdraw_6, 0.600000, 2.000000);
TextDrawTextSize(textdraw_6, 16.500000, 16.500000);
TextDrawSetOutline(textdraw_6, 1);
TextDrawSetShadow(textdraw_6, 0);
TextDrawAlignment(textdraw_6, 1);
TextDrawColor(textdraw_6, -1);
TextDrawBackgroundColor(textdraw_6, 255);
TextDrawBoxColor(textdraw_6, 50);
TextDrawUseBox(textdraw_6, 1);
TextDrawSetProportional(textdraw_6, 1);
TextDrawSetSelectable(textdraw_6, 0);

textdraw_7 = TextDrawCreate(282.000000, 77.000000, "your_level");
TextDrawFont(textdraw_7, 3);
TextDrawLetterSize(textdraw_7, 0.600000, 2.000000);
TextDrawTextSize(textdraw_7, 400.000000, 17.000000);
TextDrawSetOutline(textdraw_7, 0);
TextDrawSetShadow(textdraw_7, 0);
TextDrawAlignment(textdraw_7, 1);
TextDrawColor(textdraw_7, -1);
TextDrawBackgroundColor(textdraw_7, 255);
TextDrawBoxColor(textdraw_7, 50);
TextDrawUseBox(textdraw_7, 0);
TextDrawSetProportional(textdraw_7, 1);
TextDrawSetSelectable(textdraw_7, 0);

textdraw_8 = TextDrawCreate(7.000000, 212.000000, "HUD:radardisc");
TextDrawFont(textdraw_8, 4);
TextDrawLetterSize(textdraw_8, 0.600000, 2.000000);
TextDrawTextSize(textdraw_8, 50.500000, 171.500000);
TextDrawSetOutline(textdraw_8, 1);
TextDrawSetShadow(textdraw_8, 0);
TextDrawAlignment(textdraw_8, 1);
TextDrawColor(textdraw_8, -1);
TextDrawBackgroundColor(textdraw_8, 255);
TextDrawBoxColor(textdraw_8, 50);
TextDrawUseBox(textdraw_8, 1);
TextDrawSetProportional(textdraw_8, 1);
TextDrawSetSelectable(textdraw_8, 0);

textdraw_9 = TextDrawCreate(3.000000, 374.000000, "ld_dual:dark");
TextDrawFont(textdraw_9, 4);
TextDrawLetterSize(textdraw_9, 0.600000, 2.000000);
TextDrawTextSize(textdraw_9, 16.500000, 16.500000);
TextDrawSetOutline(textdraw_9, 1);
TextDrawSetShadow(textdraw_9, 0);
TextDrawAlignment(textdraw_9, 1);
TextDrawColor(textdraw_9, -1);
TextDrawBackgroundColor(textdraw_9, 255);
TextDrawBoxColor(textdraw_9, 50);
TextDrawUseBox(textdraw_9, 1);
TextDrawSetProportional(textdraw_9, 1);
TextDrawSetSelectable(textdraw_9, 0);

textdraw_10 = TextDrawCreate(61.000000, 213.000000, "pl/fps/ping_labels");
TextDrawFont(textdraw_10, 3);
TextDrawLetterSize(textdraw_10, 0.600000, 2.000000);
TextDrawTextSize(textdraw_10, 400.000000, 17.000000);
TextDrawSetOutline(textdraw_10, 0);
TextDrawSetShadow(textdraw_10, 0);
TextDrawAlignment(textdraw_10, 1);
TextDrawColor(textdraw_10, -1);
TextDrawBackgroundColor(textdraw_10, 255);
TextDrawBoxColor(textdraw_10, 50);
TextDrawUseBox(textdraw_10, 0);
TextDrawSetProportional(textdraw_10, 1);
TextDrawSetSelectable(textdraw_10, 0);

textdraw_11 = TextDrawCreate(318.000000, 283.000000, "got_it!");
TextDrawFont(textdraw_11, 2);
TextDrawLetterSize(textdraw_11, 0.545830, 2.600002);
TextDrawTextSize(textdraw_11, 400.000000, 111.000000);
TextDrawSetOutline(textdraw_11, 0);
TextDrawSetShadow(textdraw_11, 0);
TextDrawAlignment(textdraw_11, 2);
TextDrawColor(textdraw_11, 16777215);
TextDrawBackgroundColor(textdraw_11, -1378294017);
TextDrawBoxColor(textdraw_11, 65449);
TextDrawUseBox(textdraw_11, 1);
TextDrawSetProportional(textdraw_11, 1);
TextDrawSetSelectable(textdraw_11, 0);


//SHOW/HIDE
TextDrawShowForPlayer(playerid, pleveltd); //Shows Textdraw for Player.
TextDrawShowForAll(pleveltd); //Shows Textdraw for all players.

TextDrawHideForPlayer(playerid, pleveltd); //Hides TextDraw for player.
TextDrawHideForAll(pleveltd); //Hides Textdraw for all players.

PlayerTextDrawShow(playerid, pleveltd[playerid]); //Shows PlayerTextDraw for player.
PlayerTextDrawHide(playerid, pleveltd[playerid]); //Hides PlayerTextDraw for player.
