/*
This script has been generated by Nickk's TextDraw editor
Author is Nickk888
*/

//VARIABLES
new Text:textdraw_0;
new PlayerText:textdraw_1[MAX_PLAYERS];
new PlayerText:textdraw_2[MAX_PLAYERS];
new PlayerText:textdraw_3[MAX_PLAYERS];
new PlayerText:textdraw_4[MAX_PLAYERS];
new Text:textdraw_5;

//TEXTDRAWS
textdraw_0 = TextDrawCreate(72.000000, 149.000000, "_");
TextDrawFont(textdraw_0, 1);
TextDrawLetterSize(textdraw_0, 0.670833, 19.249975);
TextDrawTextSize(textdraw_0, 305.000000, 99.000000);
TextDrawSetOutline(textdraw_0, 0);
TextDrawSetShadow(textdraw_0, 0);
TextDrawAlignment(textdraw_0, 2);
TextDrawColor(textdraw_0, -256);
TextDrawBackgroundColor(textdraw_0, 255);
TextDrawBoxColor(textdraw_0, 135);
TextDrawUseBox(textdraw_0, 1);
TextDrawSetProportional(textdraw_0, 1);
TextDrawSetSelectable(textdraw_0, 0);

textdraw_1[playerid] = CreatePlayerTextDraw(playerid, 27.000000, 156.000000, "~b~Name:_~w~GameOvr~n~~b~Ping:_~w~180~n~~b~FPS:_~w~50~n~~b~PL:_~w~0.1~n~~b~Vehicle:_~w~Bullet~n~~b~Weapon_1:_~w~Wep_Name");
PlayerTextDrawFont(playerid, textdraw_1[playerid], 1);
PlayerTextDrawLetterSize(playerid, textdraw_1[playerid], 0.200000, 1.000000);
PlayerTextDrawTextSize(playerid, textdraw_1[playerid], 413.500000, 13.000000);
PlayerTextDrawSetOutline(playerid, textdraw_1[playerid], 0);
PlayerTextDrawSetShadow(playerid, textdraw_1[playerid], 1);
PlayerTextDrawAlignment(playerid, textdraw_1[playerid], 1);
PlayerTextDrawColor(playerid, textdraw_1[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, textdraw_1[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_1[playerid], 50);
PlayerTextDrawUseBox(playerid, textdraw_1[playerid], 0);
PlayerTextDrawSetProportional(playerid, textdraw_1[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_1[playerid], 0);

textdraw_2[playerid] = CreatePlayerTextDraw(playerid, 27.000000, 210.000000, "~b~Weapon_2:_~w~Wep_Name~n~~b~Weapon_3:_~w~Wep_Name~n~~b~Weapon_4:_~w~Wep_Name~n~~b~Weapon_5:_~w~Wep_Name");
PlayerTextDrawFont(playerid, textdraw_2[playerid], 1);
PlayerTextDrawLetterSize(playerid, textdraw_2[playerid], 0.200000, 1.000000);
PlayerTextDrawTextSize(playerid, textdraw_2[playerid], 413.500000, 13.000000);
PlayerTextDrawSetOutline(playerid, textdraw_2[playerid], 0);
PlayerTextDrawSetShadow(playerid, textdraw_2[playerid], 1);
PlayerTextDrawAlignment(playerid, textdraw_2[playerid], 1);
PlayerTextDrawColor(playerid, textdraw_2[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, textdraw_2[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_2[playerid], 50);
PlayerTextDrawUseBox(playerid, textdraw_2[playerid], 0);
PlayerTextDrawSetProportional(playerid, textdraw_2[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_2[playerid], 0);

textdraw_3[playerid] = CreatePlayerTextDraw(playerid, 27.000000, 246.000000, "~b~Weapon_6:_~w~Wep_Name~n~~b~Weapon_7:_~w~Wep_Name~n~~b~Weapon_8:_~w~Wep_Name~n~~b~Weapon_9:_~w~Wep_Name");
PlayerTextDrawFont(playerid, textdraw_3[playerid], 1);
PlayerTextDrawLetterSize(playerid, textdraw_3[playerid], 0.200000, 1.000000);
PlayerTextDrawTextSize(playerid, textdraw_3[playerid], 413.500000, 13.000000);
PlayerTextDrawSetOutline(playerid, textdraw_3[playerid], 0);
PlayerTextDrawSetShadow(playerid, textdraw_3[playerid], 1);
PlayerTextDrawAlignment(playerid, textdraw_3[playerid], 1);
PlayerTextDrawColor(playerid, textdraw_3[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, textdraw_3[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_3[playerid], 50);
PlayerTextDrawUseBox(playerid, textdraw_3[playerid], 0);
PlayerTextDrawSetProportional(playerid, textdraw_3[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_3[playerid], 0);

textdraw_4[playerid] = CreatePlayerTextDraw(playerid, 27.000000, 282.000000, "~b~Weapon_10:_~w~Wep_Name~n~~b~Weapon_11:_~w~Wep_Name~n~~b~Weapon_12:_~w~Wep_Name~n~~b~Weapon_13:_~w~Wep_Name");
PlayerTextDrawFont(playerid, textdraw_4[playerid], 1);
PlayerTextDrawLetterSize(playerid, textdraw_4[playerid], 0.200000, 1.000000);
PlayerTextDrawTextSize(playerid, textdraw_4[playerid], 413.500000, 13.000000);
PlayerTextDrawSetOutline(playerid, textdraw_4[playerid], 0);
PlayerTextDrawSetShadow(playerid, textdraw_4[playerid], 1);
PlayerTextDrawAlignment(playerid, textdraw_4[playerid], 1);
PlayerTextDrawColor(playerid, textdraw_4[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, textdraw_4[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_4[playerid], 50);
PlayerTextDrawUseBox(playerid, textdraw_4[playerid], 0);
PlayerTextDrawSetProportional(playerid, textdraw_4[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_4[playerid], 0);

textdraw_5 = TextDrawCreate(39.000000, 139.000000, "~y~spec_info");
TextDrawFont(textdraw_5, 3);
TextDrawLetterSize(textdraw_5, 0.416666, 1.650000);
TextDrawTextSize(textdraw_5, 400.000000, 17.000000);
TextDrawSetOutline(textdraw_5, 1);
TextDrawSetShadow(textdraw_5, 0);
TextDrawAlignment(textdraw_5, 1);
TextDrawColor(textdraw_5, -1);
TextDrawBackgroundColor(textdraw_5, 255);
TextDrawBoxColor(textdraw_5, 50);
TextDrawUseBox(textdraw_5, 0);
TextDrawSetProportional(textdraw_5, 1);
TextDrawSetSelectable(textdraw_5, 0);


//SHOW/HIDE
TextDrawShowForPlayer(playerid, textdraw_0); //Shows Textdraw for Player.
TextDrawShowForAll(textdraw_0); //Shows Textdraw for all players.

TextDrawHideForPlayer(playerid, textdraw_0); //Hides TextDraw for player.
TextDrawHideForAll(textdraw_0); //Hides Textdraw for all players.

PlayerTextDrawShow(playerid, textdraw_0[playerid]); //Shows PlayerTextDraw for player.
PlayerTextDrawHide(playerid, textdraw_0[playerid]); //Hides PlayerTextDraw for player.
