/*
This script has been generated by Nickk's TextDraw editor
Author is Nickk888
*/

//VARIABLES
new Text:connecttd[4];
new Text:connecttd[5];
new Text:connecttd[6];
new Text:connecttd[7];
new Text:connecttd[8];
new Text:connecttd[9];
new Text:connecttd[10];
new Text:connecttd[11];

//TEXTDRAWS
connecttd[4] = TextDrawCreate(208.000000, 20.000000, "l_Lazer_l~n~______l_Gaming_l~n~______________l_Gang_l~n~____________________l_WarZ_l");
TextDrawFont(connecttd[4], 1);
TextDrawLetterSize(connecttd[4], 0.537500, 2.149991);
TextDrawTextSize(connecttd[4], 400.000000, 17.000000);
TextDrawSetOutline(connecttd[4], 0);
TextDrawSetShadow(connecttd[4], 2);
TextDrawAlignment(connecttd[4], 1);
TextDrawColor(connecttd[4], -1);
TextDrawBackgroundColor(connecttd[4], 255);
TextDrawBoxColor(connecttd[4], 50);
TextDrawUseBox(connecttd[4], 0);
TextDrawSetProportional(connecttd[4], 1);
TextDrawSetSelectable(connecttd[4], 0);

connecttd[5] = TextDrawCreate(154.000000, 372.000000, "Place_where_the_Next_Gen_Gang_WarZ_begins...");
TextDrawFont(connecttd[5], 1);
TextDrawLetterSize(connecttd[5], 0.362499, 1.299998);
TextDrawTextSize(connecttd[5], 400.000000, 17.000000);
TextDrawSetOutline(connecttd[5], 3);
TextDrawSetShadow(connecttd[5], 0);
TextDrawAlignment(connecttd[5], 1);
TextDrawColor(connecttd[5], -1);
TextDrawBackgroundColor(connecttd[5], 255);
TextDrawBoxColor(connecttd[5], 50);
TextDrawUseBox(connecttd[5], 0);
TextDrawSetProportional(connecttd[5], 1);
TextDrawSetSelectable(connecttd[5], 0);

connecttd[6] = TextDrawCreate(460.000000, -6.000000, "Preview_Model");
TextDrawFont(connecttd[6], 5);
TextDrawLetterSize(connecttd[6], 0.600000, 2.000000);
TextDrawTextSize(connecttd[6], 103.500000, 105.000000);
TextDrawSetOutline(connecttd[6], 0);
TextDrawSetShadow(connecttd[6], 0);
TextDrawAlignment(connecttd[6], 1);
TextDrawColor(connecttd[6], -1);
TextDrawBackgroundColor(connecttd[6], 0);
TextDrawBoxColor(connecttd[6], 0);
TextDrawUseBox(connecttd[6], 0);
TextDrawSetProportional(connecttd[6], 1);
TextDrawSetSelectable(connecttd[6], 0);
TextDrawSetPreviewModel(connecttd[6], 106);
TextDrawSetPreviewRot(connecttd[6], -10.000000, 0.000000, -20.000000, 1.000000);
TextDrawSetPreviewVehCol(connecttd[6], 1, 1);

connecttd[7] = TextDrawCreate(406.000000, -6.000000, "Preview_Model");
TextDrawFont(connecttd[7], 5);
TextDrawLetterSize(connecttd[7], 0.600000, 2.000000);
TextDrawTextSize(connecttd[7], 103.500000, 105.000000);
TextDrawSetOutline(connecttd[7], 0);
TextDrawSetShadow(connecttd[7], 0);
TextDrawAlignment(connecttd[7], 1);
TextDrawColor(connecttd[7], -1);
TextDrawBackgroundColor(connecttd[7], 0);
TextDrawBoxColor(connecttd[7], 0);
TextDrawUseBox(connecttd[7], 0);
TextDrawSetProportional(connecttd[7], 1);
TextDrawSetSelectable(connecttd[7], 0);
TextDrawSetPreviewModel(connecttd[7], 116);
TextDrawSetPreviewRot(connecttd[7], -10.000000, 0.000000, -20.000000, 1.000000);
TextDrawSetPreviewVehCol(connecttd[7], 1, 1);

connecttd[8] = TextDrawCreate(517.000000, -6.000000, "Preview_Model");
TextDrawFont(connecttd[8], 5);
TextDrawLetterSize(connecttd[8], 0.600000, 2.000000);
TextDrawTextSize(connecttd[8], 103.500000, 105.000000);
TextDrawSetOutline(connecttd[8], 0);
TextDrawSetShadow(connecttd[8], 0);
TextDrawAlignment(connecttd[8], 1);
TextDrawColor(connecttd[8], -1);
TextDrawBackgroundColor(connecttd[8], 0);
TextDrawBoxColor(connecttd[8], 0);
TextDrawUseBox(connecttd[8], 0);
TextDrawSetProportional(connecttd[8], 1);
TextDrawSetSelectable(connecttd[8], 0);
TextDrawSetPreviewModel(connecttd[8], 284);
TextDrawSetPreviewRot(connecttd[8], -10.000000, 0.000000, -20.000000, 1.000000);
TextDrawSetPreviewVehCol(connecttd[8], 1, 1);

connecttd[9] = TextDrawCreate(130.000000, -6.000000, "Preview_Model");
TextDrawFont(connecttd[9], 5);
TextDrawLetterSize(connecttd[9], 0.600000, 2.000000);
TextDrawTextSize(connecttd[9], 103.500000, 105.000000);
TextDrawSetOutline(connecttd[9], 0);
TextDrawSetShadow(connecttd[9], 0);
TextDrawAlignment(connecttd[9], 1);
TextDrawColor(connecttd[9], -1);
TextDrawBackgroundColor(connecttd[9], 0);
TextDrawBoxColor(connecttd[9], 0);
TextDrawUseBox(connecttd[9], 0);
TextDrawSetProportional(connecttd[9], 1);
TextDrawSetSelectable(connecttd[9], 0);
TextDrawSetPreviewModel(connecttd[9], 103);
TextDrawSetPreviewRot(connecttd[9], -10.000000, 0.000000, 11.000000, 1.000000);
TextDrawSetPreviewVehCol(connecttd[9], 1, 1);

connecttd[10] = TextDrawCreate(76.000000, -6.000000, "Preview_Model");
TextDrawFont(connecttd[10], 5);
TextDrawLetterSize(connecttd[10], 0.600000, 2.000000);
TextDrawTextSize(connecttd[10], 103.500000, 105.000000);
TextDrawSetOutline(connecttd[10], 0);
TextDrawSetShadow(connecttd[10], 0);
TextDrawAlignment(connecttd[10], 1);
TextDrawColor(connecttd[10], -1);
TextDrawBackgroundColor(connecttd[10], 0);
TextDrawBoxColor(connecttd[10], 0);
TextDrawUseBox(connecttd[10], 0);
TextDrawSetProportional(connecttd[10], 1);
TextDrawSetSelectable(connecttd[10], 0);
TextDrawSetPreviewModel(connecttd[10], 110);
TextDrawSetPreviewRot(connecttd[10], -10.000000, 0.000000, 11.000000, 1.000000);
TextDrawSetPreviewVehCol(connecttd[10], 1, 1);

connecttd[11] = TextDrawCreate(24.000000, -6.000000, "Preview_Model");
TextDrawFont(connecttd[11], 5);
TextDrawLetterSize(connecttd[11], 0.600000, 2.000000);
TextDrawTextSize(connecttd[11], 103.500000, 105.000000);
TextDrawSetOutline(connecttd[11], 0);
TextDrawSetShadow(connecttd[11], 0);
TextDrawAlignment(connecttd[11], 1);
TextDrawColor(connecttd[11], -1);
TextDrawBackgroundColor(connecttd[11], 0);
TextDrawBoxColor(connecttd[11], 0);
TextDrawUseBox(connecttd[11], 0);
TextDrawSetProportional(connecttd[11], 1);
TextDrawSetSelectable(connecttd[11], 0);
TextDrawSetPreviewModel(connecttd[11], 163);
TextDrawSetPreviewRot(connecttd[11], -10.000000, 0.000000, 11.000000, 1.000000);
TextDrawSetPreviewVehCol(connecttd[11], 1, 1);


//SHOW/HIDE
TextDrawShowForPlayer(playerid, connecttd[4]); //Shows Textdraw for Player.
TextDrawShowForAll(connecttd[4]); //Shows Textdraw for all players.

TextDrawHideForPlayer(playerid, connecttd[4]); //Hides TextDraw for player.
TextDrawHideForAll(connecttd[4]); //Hides Textdraw for all players.

PlayerTextDrawShow(playerid, connecttd[4][playerid]); //Shows PlayerTextDraw for player.
PlayerTextDrawHide(playerid, connecttd[4][playerid]); //Hides PlayerTextDraw for player.
