/*
This script has been generated by Nickk's TextDraw editor
Author is Nickk888
*/

//VARIABLES
new Text:LGGW[9];

//TEXTDRAWS
LGGW[9] = TextDrawCreate(559.000000, 103.000000, "LGGW_~w~1.03");
TextDrawFont(LGGW[9], 2);
TextDrawLetterSize(LGGW[9], 0.241666, 1.249999);
TextDrawTextSize(LGGW[9], 606.000000, 480);
TextDrawSetOutline(LGGW[9], 0);
TextDrawSetShadow(LGGW[9], 1);
TextDrawAlignment(LGGW[9], 1);
TextDrawColor(LGGW[9], -1962934017);
TextDrawBackgroundColor(LGGW[9], 255);
TextDrawBoxColor(LGGW[9], 255);
TextDrawUseBox(LGGW[9], 1);
TextDrawSetProportional(LGGW[9], 1);
TextDrawSetSelectable(LGGW[9], 0);


//SHOW/HIDE
TextDrawShowForPlayer(playerid, LGGW[9]); //Shows Textdraw for Player.
TextDrawShowForAll(LGGW[9]); //Shows Textdraw for all players.

TextDrawHideForPlayer(playerid, LGGW[9]); //Hides TextDraw for player.
TextDrawHideForAll(LGGW[9]); //Hides Textdraw for all players.

PlayerTextDrawShow(playerid, LGGW[9][playerid]); //Shows PlayerTextDraw for player.
PlayerTextDrawHide(playerid, LGGW[9][playerid]); //Hides PlayerTextDraw for player.
